sudo: required

services:
 - docker

before_install:
 - docker pull mattscode/avr-build
 - mkdir build

script:
 - docker run -v `pwd`:/src -v `pwd`/build:/build  mattscode/avr-build cmake /src
 - docker run -v `pwd`:/src -v `pwd`/build:/build  mattscode/avr-build make
 - docker run -v `pwd`:/src -v `pwd`/build:/build  mattscode/avr-build make test
